name: begin_id_sdk_dart
description: Flutter/Dart Begin Wallet Begin-ID SDK package
version: 1.0.0
homepage: https://github.com/BeginWallet/begin-id-sdk-dart.git

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
