name: Publish

on:
  release:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64
      - name: Install dependencies
      - run: flutter pub get
      - name: Analyze
        run: flutter analyze
      - name: Run tests
      - run: flutter test
      - name: Check Publish Warnings
        run: dart pub publish --dry-run
      #- name: Publish
          #uses: k-paxian/dart-package-publisher@v1.5.1
          #with:
          #credentialJson: ${{ secrets.CREDENTIAL_JSON }}
          #flutter: true
        #skipTests: true
